### ISSUE TITLE
Does not show any video

### ISSUE THREAD

**Issue by jhanc97** [LetrixZ/animeapp_spanish#1]
shows posters and episodes but does not upload any video.

"MainViewModel: onFailure: API CALL FAILED / ONGOINGS, java.net.SocketTimeoutException: timeout"

Is what e shows from android studio

**Comment by LetrixZ** [comment]
Te API is dead: https://github.com/ChrisMichaelPerezSantiago/animeflv

**Comment by jhanc97** [comment]
Fork the project and deploy it to my server, change the url in android studio

**Comment by LetrixZ** [comment]
It should be working now

**Comment by jhanc97** [comment]
@LetrixZ Shows posters and episodes but does not play any video

**Comment by jhanc97** [comment]
@LetrixZ correct now it works correctly, thank you very much.

**Comment by LetrixZ** [comment]
Keep in mind that I'm not longer developing this app. When I have time, I'll probably, if I find a good API, make a newer app. The current one is really old and the actual API is broken (search sometimes works, sometimes doesn't).
